Fix menu overlap, add UI color blocks for homepage to improve user experience
shescoding/conference-website pull request #10
Opened 2018-12-10 00:33 UTC by cherchezlafemme

- to improve user experience this PR is suggesting color blocking different sections
- also makes nav fit 1 line to avoid content clashing

This is the homepage that this PR is suggesting (only css/ui changes, no content changes):
![conf-new-home](https://user-images.githubusercontent.com/18508181/49705058-e7c43e00-fbcf-11e8-93fb-343478641c02.png)

If this looks good, I would like to also update schedule page before deploy to have same color-block style.

2018-12-10 00:34 UTC, cherchezlafemme commented
@natsteinmetz let me know your thoughts. colors can be changed, etc. I just feel that it would be cool to have the content highlighted as separate sections, for better ux.

2019-01-14 00:49 UTC, cherchezlafemme commented
Also fixes the `404 Not Found` in the main navigation. Can be reproduced in production http://techwomenrising.org/code-of-conduct.html => click on event dropdown, pick Career & community.

2019-01-14 00:50 UTC, cherchezlafemme commented
@natsteinmetz this PR fixes menu and adds some color to block out sections to make it visually more readable. I picked colors randomly :D let me know if you want different colors.

2019-01-14 00:54 UTC, cherchezlafemme commented
Also fixes how the deep links get to the info, no more heading half covered when click on about.

2019-01-14 01:05 UTC, cherchezlafemme commented
Fix the mobile view of the "Tickets coming soon" button. It overlaps in production.

2019-01-14 23:05 UTC, natsteinmetz requested changes
Hey Anya, thanks a lot for your updates! Comments below:

👍 for the navbar update, the 'About' and mobile ticket button fixes - thanks!
😿 the 404's are not fixed unfortunately. While you updated the links in the index.html file, they'll need to be updated in the schedule.html and code-of-conduct.html files too.
🎡 Regarding the color updates: Great idea! Could you try the following changes:
- Replace the light blue with the light grey. I think the fewer different colors we have, the better. One option could be to try light green in the same green family that we use right now. And if possible, I would make the background color (whether grey or green) even lighter than they are now.
-  Instead of separating every block, let's try separating every logical content block. So we would have the background on the the mailing list sign up block, the 'Sponsors & Partners' block, and then the team block.

Thanks, Anya!! ❤️

2019-01-14 23:05 UTC, natsteinmetz commented on index.html
> +          <div class="col-3 col-offset-1">
I like the way how you put the cat asset and the text into columns. But I do feel that the cat in this form is too big - can you scale it down approximately to the size it had before, or just slightly bigger?

2019-04-01 03:59 UTC, cherchezlafemme commented on index.html
> +          <div class="col-3 col-offset-1">
sounds good. will make it smaller 👍

2019-04-01 04:01 UTC, cherchezlafemme commented
@natsteinmetz cat icon and links are fixed, removed the blue section and made the color-blocks themed related. also made the grey lighter shade. I kept the shade of grey that's currently on the site for the mailing list section since it's call to action and that's what is was before. let me know if there is anything else I need to do.

2019-05-11 19:13 UTC, cherchezlafemme commented
@natsteinmetz let me know if there is anything else I need to do on this PR. Thank you!

2021-02-16 17:55 UTC, closed without merging